### PR TITLE
formatting, add URLs to each library

### PR DESCRIPTION
**Pull request by attritionorg**
formatting, add URLs to each library

### CODE REVIEW

**Comment by davidski** [comment]
Thanks for the PR! :bow:

I'm not familiar with the URL reference syntax you're using. Travis builds under Python 2.6 and 2.7 are failing with this change. Can you provide a pointer to this syntax and/or refactor this PR to be compatible with those versions of python?

**Comment by attritionorg** [comment]
I didn't realize this file was auto-parsed, my mistake! Can kill the PR, or move the gist of it to README.md instead. There is often confusion over library names due to forks, projects moving, etc. Figured it might help.

**Comment by davidski** [comment]
No worries! There's a heck of a lot about python package creation that is still new to me.

I'm happy to rework this into the README. If you have the time to take a crack at that, that would be great. Otherwise, it may have to wait until the weekend for me. I'll also have to fight my deep desire to remove the dependency on `pandas`. That brings in a ton of heavy code for not much benefit in the current train.

**Comment by attritionorg** [comment]
Reject this PR, I will work it into the main README, only take a couple minutes!

**Comment by davidski** [comment]
Closing per discussion.

**Pull request closed without merging**
